php8 and phplint

diff --git a/run b/run
--- a/run
+++ b/run
@@ -20,12 +20,21 @@ function php-cs-fixer() {
   #vendor/bin/php-cs-fixer fix -v --config .php_cs.legacy
 }
 
+function phplint() {
+  if [[ ! -e ./vendor/bin/phplint ]]; then
+    echo "The vendor/bin/phplint file is missing. Did you install the dependencies?"
+    exit 1
+  fi
+
+  vendor/bin/phplint
+}
 
 function usage() {
   cat <<HEREDOC
 Usage: ./run [task]
   phpunit       Run PhpUnit (not yet supported)
-  php-cs-fixer  Run the PHP-CS-Fixer
+  php-cs-fixer  Run PHP-CS-Fixer
+  phplint       Run PHPLint
 HEREDOC
 }
 
@@ -36,6 +45,10 @@ case "$1" in
   ;;
   php-cs-fixer)
     php-cs-fixer
+    exit 0
+  ;;
+  phplint)
+    phplint
     exit 0
   ;;
   *)
